server:
  port: 8080
logging:
  level:
    root: INFO
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/epass
    data-username: root
    data-password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true