spring:
  profiles:
    active:
    - dev
  datasource:
    url: jdbc:mysql://localhost:3306/school?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
#  main:
#    banner-mode: off
  messages:
    basename: exception/message # Comma-separated list of basenames, each following the ResourceBundle convention.
    cache-seconds: -1 # Loaded resource bundle files cache expiration, in seconds. When set to -1, bundles are cached forever.
    encoding: UTF-8 # Message bundles encoding.
        
  # Embedded ActiveMQ Configuration Example
  activemq:
      in-memory: true

  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: mycustomers

activemq.queueName: inmemory.queue
        
liquibase:
  change-log: classpath:db/liquibase-changelog.xml        

name: Hardik Nai(Application.properties)
company: firstai.co(Application.properties)
address: nikol(Application.properties)    

my.secret: ${random.value}
my.number: ${random.int}
my.bignumber: ${random.long}
my.uuid: ${random.uuid}
my.number.less.than.ten: ${random.int(10)}
my.number.in.range: ${random.int[1024,65536]}


foo:
  list:
    - name: MCA
      discription: Master Computer Application
    - name: BCA
      discription: Bachalor Computer Application
    - name: MBA
      discription: Master Business Application
database: 
  enable: "true"
  remoteAddress: 10.10.10.124
  security:
    username: ${os.name}${user.home}
    password: hardiknai92
    roles:
      - Admin
      - Manager
file:
  upload: data/upload/
  download: data/download/
  
  
jsa:
  aws:
    access_key_id: AKIAJECSR4N33LRHCXFA
    secret_access_key: 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
  s3:
    bucket: epass
    region: us-east-1
    uploadfile: C:\\s3\\jsa-s3-upload-file.txt
    key: jsa-s3-upload-file.txt